# Generated by Django 5.2.6 on 2025-10-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('admin', 'Administrador'), ('tecnico', 'Técnico / Diagnóstico'), ('recepcion', 'Recepción / Entrega'), ('cliente', 'Cliente')], max_length=20, null=True),
        ),
    ]
