# Generated by Django 5.2.6 on 2025-10-17 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(max_length=100)),
                ('problema_reportado', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones_cliente', to=settings.AUTH_USER_MODEL)),
                ('recepcionista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones_recepcionista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
