# Generated by Django 5.2.6 on 2025-10-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico_text', models.TextField(blank=True)),
                ('solucion_text', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('asignado', 'Asignado'), ('en_progreso', 'En progreso'), ('finalizado', 'Finalizado')], default='asignado', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
