# Generated by Django 5.2.6 on 2025-11-08 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostico',
            old_name='diagnostico_text',
            new_name='diagnostico',
        ),
        migrations.RenameField(
            model_name='diagnostico',
            old_name='solucion_text',
            new_name='solucion',
        ),
    ]
